name = "FoldsCUDA"
uuid = "6cd66ae4-5932-4b96-926d-e73e578e42cc"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.9"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
InitialValues = "22cec73e-a1b8-11e9-2c92-598750a2cf9c"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
UnionArrays = "d6dd79e4-993b-11e9-1366-0de1c9fe1122"

[compat]
CUDA = "3.8"
InitialValues = "0.2, 0.3"
Transducers = "0.4.69"
UnionArrays = "0.1.2"
julia = "1.6"
